parameters:
    database_host: 127.0.0.1
    database_port: ~
    database_name: music
    database_user: root
    database_password: root
    # You should uncomment this if you want to use pdo_sqlite
    #database_path: '%kernel.project_dir%/var/data/data.sqlite'

    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: ~
    mailer_password: ~

    secret: 'this-is-not-secret'